[build]
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

# Scheduled function to run every hour
[functions.scheduled-update]
  schedule = "@hourly"

# Alternative hourly function (for testing)
[functions.hourly-update]
  schedule = "@hourly"

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/manual-update"
  to = "/.netlify/functions/manual-update"
  status = 200

[[redirects]]
  from = "/scheduled-update"
  to = "/.netlify/functions/scheduled-update"
  status = 200

[[redirects]]
  from = "/hourly-update"
  to = "/.netlify/functions/hourly-update"
  status = 200 