[build]
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

# Daily update function (can be scheduled later)
# [functions.daily-update]
#   schedule = "@daily"



[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/manual-update"
  to = "/.netlify/functions/manual-update"
  status = 200

[[redirects]]
  from = "/daily-update"
  to = "/.netlify/functions/daily-update"
  status = 200



[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200 